У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tips.csv")

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.shape

(244, 7)

In [5]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [7]:
df["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [56]:
df[["total_bill", "tip"]]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [8]:
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [9]:
df.loc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [10]:
total_bill_more_than_20 = df[df["total_bill"] > 20]
print(f" Кількість записів, де всі рахунки більше 20 доларів: {len(total_bill_more_than_20)}")
display(total_bill_more_than_20.head())

 Кількість записів, де всі рахунки більше 20 доларів: 97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [11]:
female_visitors = df[df["sex"] == "Female"]
print(f"Кількість записів, де всі відвідувачі-жінки: {len(female_visitors)}")
display(female_visitors.head())

Кількість записів, де всі відвідувачі-жінки: 87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [12]:
dinner_bills = df[df["time"] == "Dinner"]
print(f"Рахунків на вечерю: {len(dinner_bills)}")
display(dinner_bills.head())

Рахунків на вечерю: 176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
dinner_bills_over_30 = df[(df["time"] == "Dinner") & (df["total_bill"] > 30)]
print(f"Рахунки на вечерю з сумою чеку більше 30 доларів: {len(dinner_bills_over_30)}")
display(dinner_bills_over_30.head())

Рахунки на вечерю з сумою чеку більше 30 доларів: 27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [14]:
total_bill_mean = df["total_bill"].mean().round(2)
tips_max = df["tip"].max()
df_na = df.isna().sum()
time_value_counts = df["time"].value_counts()

print(f"Середній розмір рахунку на всьому наборі даних: {total_bill_mean}")
print("----------")
print(f"Максимальні чайові: {tips_max}")
print("----------")
print(f"Кількість пропущених значень у всіх колонках:\n {df_na}")
print("----------")
print(f"Скільки в наборі даних рахунків за обіди і за вечері:\n {time_value_counts}")

Середній розмір рахунку на всьому наборі даних: 19.79
----------
Максимальні чайові: 10.0
----------
Кількість пропущених значень у всіх колонках:
 total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64
----------
Скільки в наборі даних рахунків за обіди і за вечері:
 time
Dinner    176
Lunch      68
Name: count, dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [15]:
avg_bill_by_gender = df.groupby("sex")["total_bill"].mean().round(2)
avg_tips_by_week_day = df.groupby("day")["tip"].mean().round(2)
num_visitors_each_day = df.groupby("day")["size"].sum()

print(f"Середній рахунок за статтю:\n {avg_bill_by_gender}")
print("----------")
print(f"Середні чайові за днем тижня:\n {avg_tips_by_week_day}")
print("----------")
print(f"Відвідувачів у кожен день:\n {num_visitors_each_day}")

Середній рахунок за статтю:
 sex
Female    18.06
Male      20.74
Name: total_bill, dtype: float64
----------
Середні чайові за днем тижня:
 day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64
----------
Відвідувачів у кожен день:
 day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [16]:
df["tip_percentage"] = ((df["tip"] / df["total_bill"]) * 100).round(2)
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            5.94
1       10.34  1.66    Male     No  Sun  Dinner     3           16.05
2       21.01  3.50    Male     No  Sun  Dinner     3           16.66
3       23.68  3.31    Male     No  Sun  Dinner     2           13.98
4       24.59  3.61  Female     No  Sun  Dinner     4           14.68
5       25.29  4.71    Male     No  Sun  Dinner     4           18.62
6        8.77  2.00    Male     No  Sun  Dinner     2           22.81
7       26.88  3.12    Male     No  Sun  Dinner     4           11.61
8       15.04  1.96    Male     No  Sun  Dinner     2           13.03
9       14.78  3.23    Male     No  Sun  Dinner     2           21.85

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [17]:
sort_total_bill = df.sort_values(["total_bill"])
sort_total_bill

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
172        7.25   5.15    Male    Yes   Sun  Dinner     2           71.03
149        7.51   2.00    Male     No  Thur   Lunch     2           26.63
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3            7.72
156       48.17   5.00    Male     No   Sun  Dinner     6           10.38
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68

[244 rows x 8 columns]

In [18]:
sort_tip = df.sort_values(["tip"], ascending=False)
sort_tip

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
23        39.42   7.58    Male     No   Sat  Dinner     4           19.23
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
141       34.30   6.70    Male     No  Thur   Lunch     6           19.53
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2            5.94
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
236       12.60   1.00    Male    Yes   Sat  Dinner     2            7.94

[244 rows x 8 columns]

In [19]:
largest_5_tip = df.nlargest(5, "tip")
largest_5_tip

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53